version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkinsWorker
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    networks:
      - ansible_my_bridge_network


networks:
  ansible_my_bridge_network:
    external: true