FROM ubuntu:22.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV POETRY_VERSION=1.5.1

WORKDIR /code

#BASIC
RUN apt-get update && apt-get install -y iputils-ping 
RUN apt-get install -y curl
RUN apt-get install -y iproute2
RUN apt-get install -y wget
RUN apt-get install -y gnupg
RUN apt-get install -y net-tools
RUN apt-get install -y openssh-server

#ANSIBLE 
RUN apt-get install -y ansible
