---
- name: Configure Server
  hosts: server
  tasks:
    - name: Clone the repo
      git:
        repo: https://github.com/jroslindo/jenkins_ansible_learning
        dest: /my_application
      become: yes

    - name: Install packages using poetry
      command: $HOME/.local/bin/poetry install --no-root
      args:
        chdir: /my_application/server
      become: yes

    - name: restart application
      command: supervisorctl restart myapp
      become: yes
      ignore_errors: yes
